# -*- coding: utf-8 -*-
"""All_ML_Process.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mwh6PXjygSszddZ0Wxw2QSuEI-XmAaM3

#**1_data_ingestion**

##**Install Dependencies**
"""

!pip uninstall -y datasets
!pip install datasets==2.14.7
!pip install pyspark
!pip install pyarrow

"""##**Spark Session Configuration**"""

from pyspark.sql import SparkSession

spark = SparkSession.builder \
    .appName("AmazonReviewsBigData") \
    .config("spark.executor.memory", "4g") \
    .config("spark.driver.memory", "4g") \
    .config("spark.sql.shuffle.partitions", "200") \
    .getOrCreate()

spark

"""##**Load Dataset (Streaming)**"""

from datasets import load_dataset

dataset = load_dataset(
    "McAuley-Lab/Amazon-Reviews-2023",
    "raw_review_Electronics",
    split="full",
    streaming=True
)

dataset

"""##**Sample ~1.5 Million Records**"""

import itertools
import pandas as pd
from pyspark.sql import SparkSession

spark = SparkSession.builder.getOrCreate()

batch = list(itertools.islice(dataset, 200000))  # take 200k rows first
pdf = pd.DataFrame(batch)
spark_df = spark.createDataFrame(pdf)

spark_df.show(5)

"""##**Validate Big Data Size**"""

print("Total Rows:", spark_df.count())
spark_df.printSchema()

"""##**Repartition for Parallelism**"""

spark_df = spark_df.repartition(200)
print("Partitions:", spark_df.rdd.getNumPartitions())

spark_df.write.mode("overwrite").parquet("data/amazon_reviews_parquet")

"""#**2_feature_engineering**"""



"""##**Load Data**"""

from pyspark.sql import SparkSession
from pyspark.sql.functions import col

spark = SparkSession.builder.getOrCreate()

df = spark.read.parquet("data/amazon_reviews_parquet")
df.show(5)

"""##**Select Text + Rating**"""

df = df.select(
    col("text").alias("review_text"),
    col("rating").alias("stars")
)

df = df.withColumn("label", col("stars") - 1)

"""##**Split Train/Test**"""

train_df, test_df = df.randomSplit([0.8, 0.2], seed=42)

"""##**NLP Pipeline**"""

from pyspark.ml.feature import Tokenizer, StopWordsRemover, HashingTF, IDF
from pyspark.ml import Pipeline

tokenizer = Tokenizer(inputCol="review_text", outputCol="words")
remover = StopWordsRemover(inputCol="words", outputCol="filtered")
hashingTF = HashingTF(inputCol="filtered", outputCol="rawFeatures", numFeatures=20000)
idf = IDF(inputCol="rawFeatures", outputCol="features")

pipeline = Pipeline(stages=[tokenizer, remover, hashingTF, idf])

model = pipeline.fit(train_df)

train_data = model.transform(train_df)
test_data = model.transform(test_df)

"""##**Persist Features**"""

train_data.persist()
test_data.persist()

train_data.count()

"""**Save Feature Data**"""

train_data.write.mode("overwrite").parquet("data/train_features")
test_data.write.mode("overwrite").parquet("data/test_features")

"""#**3_model_training**

##**Load Feature Data**
"""

from pyspark.sql import SparkSession

spark = SparkSession.builder.getOrCreate()

train_data = spark.read.parquet("data/train_features")
test_data = spark.read.parquet("data/test_features")

"""##**Logistic Regression**"""

from pyspark.ml.classification import LogisticRegression

lr = LogisticRegression(featuresCol="features", labelCol="label", maxIter=20)
lr_model = lr.fit(train_data)

lr_model.write().overwrite().save("models/lr_model")

"""##**Naive Bayes**"""

from pyspark.ml.classification import NaiveBayes

nb = NaiveBayes(featuresCol="features", labelCol="label")
nb_model = nb.fit(train_data)

nb_model.write().overwrite().save("models/nb_model")

"""##**Random Forest**"""

from pyspark.ml.classification import RandomForestClassifier

rf = RandomForestClassifier(featuresCol="features", labelCol="label", numTrees=50)
rf_model = rf.fit(train_data)

rf_model.write().overwrite().save("models/rf_model")

"""##**SVM (OneVsRest)**"""

from pyspark.ml.classification import LinearSVC, OneVsRest

lsvc = LinearSVC(featuresCol="features", labelCol="label")
ovr = OneVsRest(classifier=lsvc)

svm_model = ovr.fit(train_data)

svm_model.write().overwrite().save("models/svm_model")

"""##**Cross Validation Example (LR)**"""

from pyspark.ml.tuning import ParamGridBuilder, CrossValidator
from pyspark.ml.evaluation import MulticlassClassificationEvaluator

evaluator = MulticlassClassificationEvaluator(metricName="accuracy")

paramGrid = ParamGridBuilder() \
    .addGrid(lr.regParam, [0.01, 0.1]) \
    .addGrid(lr.elasticNetParam, [0.0, 0.5]) \
    .build()

crossval = CrossValidator(estimator=lr,
                          estimatorParamMaps=paramGrid,
                          evaluator=evaluator,
                          numFolds=3)

cv_model = crossval.fit(train_data)

"""#**4_evaluation**

##**Load Test Data + Models**
"""

from pyspark.sql import SparkSession
from pyspark.ml.classification import LogisticRegressionModel

spark = SparkSession.builder.getOrCreate()

test_data = spark.read.parquet("data/test_features")
lr_model = LogisticRegressionModel.load("models/lr_model")

"""##**Predictions**"""

lr_predictions = lr_model.transform(test_data)

"""##**Accuracy**"""

from pyspark.ml.evaluation import MulticlassClassificationEvaluator

evaluator = MulticlassClassificationEvaluator(metricName="accuracy")
accuracy = evaluator.evaluate(lr_predictions)

print("Logistic Regression Accuracy:", accuracy)

"""##**Confusion Matrix**"""

lr_predictions.groupBy("label", "prediction").count().show()

"""##**Scalability Timing**"""

import time

start = time.time()
_ = lr_model.transform(test_data).count()
end = time.time()

print("Prediction Time:", end - start)



"""#**Export Data from Spark for Tableau**

##**Export Model Performance Metrics**
"""

from pyspark.ml.evaluation import MulticlassClassificationEvaluator
import pandas as pd

models = {
    "Logistic Regression": lr_model.transform(test_data),
    "Naive Bayes": nb_model.transform(test_data),
    "Random Forest": rf_model.transform(test_data),
    "SVM": svm_model.transform(test_data)
}

results = []

evaluator_acc = MulticlassClassificationEvaluator(metricName="accuracy")
evaluator_f1 = MulticlassClassificationEvaluator(metricName="f1")

for name, preds in models.items():
    results.append({
        "Model": name,
        "Accuracy": evaluator_acc.evaluate(preds),
        "F1 Score": evaluator_f1.evaluate(preds)
    })

results_df = pd.DataFrame(results)
results_df.to_csv("model_performance.csv", index=False)

"""###**Export Confusion Matrix Data**"""

conf_df = lr_predictions.groupBy("label", "prediction").count().toPandas()
conf_df.to_csv("confusion_matrix.csv", index=False)

"""##**Export Business Insights Data**"""

from pyspark.sql.functions import length

business_df = df.withColumn("review_length", length("review_text")) \
                .groupBy("stars") \
                .avg("review_length") \
                .toPandas()

business_df.to_csv("business_insights.csv", index=False)

"""##**Export Scalability Data**"""

import time

scalability_results = []

for partitions in [100, 200, 400]:
    spark.conf.set("spark.sql.shuffle.partitions", partitions)

    start = time.time()
    _ = lr_model.transform(test_data).count()
    end = time.time()

    scalability_results.append({
        "Partitions": partitions,
        "Execution_Time": end - start
    })

pd.DataFrame(scalability_results).to_csv("scalability_results.csv", index=False)

